version: "3.8"
services:
    pishgu:
        image: ${ARCH}pishgu:${TAG}
        build:
            context: ${PRODUCTION_PATH}
            dockerfile: Dockerfile.${ARCH}
        container_name: pishgu
        tty: true
