version: "3.8"
networks: {}
services:
    yolostereo:
        image: ${ARCH}yolostereo:${TAG}
        network_mode: host
        pid: host
        container_name: yolostereo
        env_file: $ENV_FILE
        environment:
            - DISPLAY=$DISPLAY
        privileged: true
        tty: true
        ports:
            - '8080:8080'
        ipc: host
        restart: always
        volumes:
            - type: bind
              source: ${PRODUCTION_PATH}/../docker
              target: /home/pishgu/visualDet3D/docker/scripts
            - /dev:/dev:rw
            - /dev:/dev \
        command: /bin/sh
        runtime: nvidia
