version: "3.8"
services:
    yolostereo:
        image: ${ARCH}yolostereo:${TAG}
        network_mode: host
        pid: host
        container_name: yolostereo
        env_file: $ENV_FILE
        environment:
            - DISPLAY=$DISPLAY
        privileged: true
        user: root
        tty: true
        volumes:
            - type: bind
              source: ${PRODUCTION_PATH}/../docker
              target: /home/visualDet3D/docker/scripts
            - /dev:/dev:rw
            - /dev:/dev \
        command: 