version: "3.8"
services:
    dsgn2:
        image: ${ARCH}pishgu:${TAG}
        network_mode: host
        pid: host
        container_name: pishgu
        env_file: $ENV_FILE
        environment:
            - DISPLAY=$DISPLAY
        privileged: true
        user: root
        tty: true
        volumes:
            - type: bind
              source: ${PRODUCTION_PATH}/../data
              target: /home/pishgu
            - /dev:/dev:rw
            - /dev:/dev \
        command: sh -c "cd /home/${USER}/DSGN2 && python -m pcdet.datasets.kitti.lidar_kitti_dataset create_kitti_infos && python -m pcdet.datasets.kitti.lidar_kitti_dataset create_gt_database_only --image_crops"
